<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>br.com.aula</groupId>
    <artifactId>aula-arquivos</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>parte1/parte1_1</module>
        <module>parte1/parte1_2</module>
        <module>parte2/parte2_1</module>
        <module>parte2/parte2_2</module>
        <module>parte2/parte2_3</module>
        <module>parte3/parte3_1</module>
        <module>parte3/parte3_2</module>
        <module>parte4/parte4_1</module>
        <module>parte4/parte4_2</module>
        <module>parte5</module>
        <module>parte6</module>
        <module>parte7</module>
        <module>parte8</module>
        <module>parte9</module>
        <module>parte-final</module>
    </modules>

    <properties>
        <maven.compiler.release>26</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
